/// <reference types="cypress" />

describe('Carrinho_item', () => {
    it('Adicionar carrinho item', () => {
        cy.visit('https://www.saucedemo.com');
        cy.get('[data-test=username]').type('standard_user');
        cy.get('[data-test=password]').type('secret_sauce');
        cy.get('[data-test=login-button]').click();
        cy.get('#item_4_img_link').click();
        cy.wait(500);
        cy.get('[data-test=add-to-cart-sauce-labs-backpack]').click();
        cy.wait(500);
        cy.get('[data-test=back-to-products]').click();
        cy.wait(500);
        cy.get('#item_0_title_link > .inventory_item_name').click();
        cy.wait(500);
        cy.get('[data-test=add-to-cart-sauce-labs-bike-light]').click();
        cy.wait(500);
        cy.get('[data-test=back-to-products]').click();
        cy.wait(500);
        cy.get('#item_1_title_link > .inventory_item_name').click();
        cy.wait(500);
        cy.get('[data-test=add-to-cart-sauce-labs-bolt-t-shirt]').click();
        cy.wait(500);
        cy.get('[data-test=back-to-products]').click();
        cy.wait(500);
        cy.get('#item_5_title_link > .inventory_item_name').click();
        cy.wait(500);
        cy.get('[data-test=add-to-cart-sauce-labs-fleece-jacket]').click();
        cy.wait(500);
        cy.get('[data-test=back-to-products]').click();
        cy.wait(500);
        cy.get('#item_2_title_link > .inventory_item_name').click();
        cy.wait(500);
        cy.get('[data-test=add-to-cart-sauce-labs-onesie]').click();
        cy.wait(500);
        cy.get('[data-test=back-to-products]').click();
        cy.wait(500);
        cy.get('#item_3_title_link > .inventory_item_name').click();
        cy.wait(500);
        cy.get('[data-test="add-to-cart-test.allthethings()-t-shirt-(red)"]').click();
        cy.wait(500);
        cy.get('[data-test=back-to-products]').click();
        cy.wait(500);
        cy.get('.shopping_cart_link').click();
        cy.wait(1000);
        cy.get('[data-test=remove-sauce-labs-backpack]').click();
        cy.wait(1000);
        cy.get('[data-test=continue-shopping]').click();
        cy.wait(1000);
        cy.get('[data-test=add-to-cart-sauce-labs-backpack]').click();
        cy.wait(1000);
        cy.get('.shopping_cart_link').click();
        cy.wait(1000);
        cy.get('[data-test=checkout]').click();
        cy.wait(500);
        cy.get('[data-test=cancel]').click();
        cy.wait(500);
        cy.get('.shopping_cart_link').click();
        cy.wait(1000);
        cy.get('[data-test=remove-sauce-labs-backpack]').click();
        cy.wait(1000);
        cy.get('[data-test=continue-shopping]').click();
        cy.wait(1000);
        cy.get('[data-test=add-to-cart-sauce-labs-backpack]').focus();
        cy.wait(1000);
        cy.get('[data-test=add-to-cart-sauce-labs-backpack]').click();
        cy.wait(1000);
        cy.get('.shopping_cart_link').click();
        cy.wait(1000);
        cy.get('[data-test=checkout]').click();
        cy.get('[data-test=firstName]').type('Pedro');
        cy.get('[data-test=lastName]').type('Souza');
        cy.get('[data-test=postalCode]').type('11111');
        cy.wait(500);
        cy.get('[data-test=continue]').click();
        cy.wait(500);
        cy.get('[data-test=finish]').click();
        cy.wait(500);
        cy.get('[data-test=back-to-products]').click();
    });
});